[package]
name = "ic-identity-manager"
version = "0.1.0"
authors = ["DFINITY Stiftung"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openssl = "0.10.28"
pem = "0.7.0"
ring = "0.16.11"
serde = { version = "1.0", features = ["derive"] }
ic-agent = { path = "../agent/rust" }
lazy_static = "1"
semver = { version = "0.9.0", features = ["serde"] }
serde_json = "1.0.40"

[dev-dependencies]
serde_cbor = "0.10"
tempfile = "3.1.0"
