name: Automatically update niv-managed dependencies
on:
  # Manual override, one can start the workflow by running:
  # curl -H "Accept: application/vnd.github.everest-preview+json" \
  #  -H "Authorization: token <your-token-here>" \
  #  --request POST \
  #  --data '{"event_type": "niv-updater-nudge", "client_payload": {}}' \
  #  https://api.github.com/repos/dfinity-lab/sdk/dispatches
  # https://help.github.com/en/actions/reference/events-that-trigger-workflows#external-events-repository_dispatch
  repository_dispatch:
    types: niv-updater-nudge
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 16 * * *'
jobs:
  niv-updater:
    name: 'Check for updates'
    runs-on: ubuntu-latest
    steps:
      - name: niv-updater-action
        uses: knl/niv-updater-action@v6
        with:
          whitelist: 'common,advisory-db,napalm'
          title_prefix: 'build: '
          labels: |
            automerge-squash
        env:
          GITHUB_TOKEN: ${{ secrets.NIV_UPDATER_TOKEN }}
